### ISSUE TITLE
Scenario payload should not be limited to object

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/simulator#41]
#### Describe the bug
Currently, it is not possible to define a string payload, as the scenario spec limits it to [object](https://github.com/asyncapi/fluffy-robot/blob/85f81eebae133ac7611c2ccd7336ac34ccda0b56/src/Schema/SimulationPlotSchema_0.0.1.json#L34).

However, with the AsyncAPI specification, payloads can define any payload (string, booleans, numbers, integers, nulls, objects, and so forth).

#### How to Reproduce
You should be able to define the following scenario file:

```
version: 0.0.1
plot-1:
  eps: 1
  priority: 2
  payload: 'testing'
```
